server:
  port: 80

spring:
  application:
    name: gateway-server

  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848 # 修改本机的host 文件

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # admin-service ADMIN-SERVICE  /admin-service/** -> 微服务（ADMIN-SERVICE）
      routes:
        - id: admin-service_router
          uri: lb://admin-service # 转发到那个目的地
          predicates:
            - Path=/admin/**
        - id: test_router
          uri: http://www.aliyun.com
          predicates:
            - Path=/product # /test -> http://www.aliyun.com/product

    sentinel:
      transport:
        dashboard: sentinel-server:8858 # sentinel-dashboard 放在ecs 里面
      datasource:
        ds1:
          nacos: # 使用Nacos持久化Sentinel数据，需要添加nacos-datasource的依赖
            server-addr: nacos-server:8848
            dataId: gw-flow
            ruleType: gw_flow
        ds2:
          nacos:
            server-addr: nacos-server:8848
            dataId: api-group
            ruleType: gw_api_group # 网关 + API分组的限流

  redis:
    host: 127.0.0.1
    port: 6379